// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC2Z2fVVR-8ZbREqVrxhk1x71Z5QbZ7NE',
    appId: '1:665913507149:web:ff6a2656c57b511bd38b04',
    messagingSenderId: '665913507149',
    projectId: 'ait-base',
    authDomain: 'ait-base.firebaseapp.com',
    storageBucket: 'ait-base.appspot.com',
    measurementId: 'G-SCPN3GRRT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOeosLZjXGIpDY4w4OlfYvo2_TN3Pe_3E',
    appId: '1:665913507149:android:046c88faf5b1fabfd38b04',
    messagingSenderId: '665913507149',
    projectId: 'ait-base',
    storageBucket: 'ait-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkHlVfDa1FVl5imbEC0hkQSfQCiR-8Up8',
    appId: '1:665913507149:ios:f055808622b365cfd38b04',
    messagingSenderId: '665913507149',
    projectId: 'ait-base',
    storageBucket: 'ait-base.appspot.com',
    iosBundleId: 'com.example.aitProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkHlVfDa1FVl5imbEC0hkQSfQCiR-8Up8',
    appId: '1:665913507149:ios:f055808622b365cfd38b04',
    messagingSenderId: '665913507149',
    projectId: 'ait-base',
    storageBucket: 'ait-base.appspot.com',
    iosBundleId: 'com.example.aitProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC2Z2fVVR-8ZbREqVrxhk1x71Z5QbZ7NE',
    appId: '1:665913507149:web:b57556d20df72401d38b04',
    messagingSenderId: '665913507149',
    projectId: 'ait-base',
    authDomain: 'ait-base.firebaseapp.com',
    storageBucket: 'ait-base.appspot.com',
    measurementId: 'G-RQ5SXN81JH',
  );
}
